HandsOn - Predict The Data Scientists Salary In India from kaggle use sklearn dataset: Predict-The-Data-Scientists-Salary-In-India_Train_Dataset.csv Data Features: Name of the company (Encoded) Years of experience(split to min and max experience) Job description Job designation Job Type Key skills Location (needs LabelEncoded) Salary in Rupees Lakhs(To be predicted)(needs LabelEncoded)
Find the best estimator among below clf1 = DecisionTreeClassifier() clf2 = RandomForestClassifier(n_estimators=100) clf3 = ExtraTreesClassifier(n_estimators=100) clf4 = AdaBoostClassifier(n_estimators=100) clf5 = GradientBoostingClassifier(n_estimators=100)

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.pipeline import * 
from sklearn.naive_bayes import * 
from sklearn.cluster import *  
from sklearn.covariance import *  
from sklearn.cross_decomposition import *  
from sklearn.datasets import *  
from sklearn.decomposition import *  
from sklearn.ensemble import *  
from sklearn.feature_extraction import *  
from sklearn.feature_extraction.text import *  
from sklearn.feature_selection import *  
from sklearn.gaussian_process import *  
from sklearn.linear_model import *  
from sklearn.manifold import *  
from sklearn.metrics import *  
from sklearn.mixture import *  
from sklearn.model_selection import *  
from sklearn.neighbors import *  
from sklearn.neural_network import *  
from sklearn.preprocessing import *  
from sklearn_pandas import DataFrameMapper
from sklearn.svm import *  
from sklearn.tree import *  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:

import keras_tuner
import keras
from keras.models import Sequential, load_model
from keras.layers import Dense, Input
from keras.wrappers import SKLearnClassifier
import keras.utils 
from keras.callbacks import * 

In [5]:
#loading datsset
scientist_sal = pd.read_csv('code\data\Predict-The-Data-Scientists-Salary-In-India_Train_Dataset.csv')

In [6]:

scientist_sal.head()

Unnamed: 0 experience                                    job_description  \
0           0    5-7 yrs  Exp: Minimum 5 years;Good understanding of IOC...   
1           1  10-17 yrs  He should have handled a team of atleast 5-6 d...   
2           2    5-9 yrs  Must be an effective communicator (written & s...   
3           3   7-10 yrs  7  -  10 years of overall experience in data e...   
4           4    1-3 yrs  Chartered Accountancy degree or MBA in Finance...   

                                           job_desig   job_type  \
0        Senior Exploit and Vulnerability Researcher        NaN   
1                                           Head SCM        NaN   
2  Deputy Manager - Talent Management & Leadershi...  Analytics   
3                 Associate Manager Data Engineering  Analytics   
4                            TS- GSA- Senior Analyst        NaN   

                                          key_skills               location  \
0  team skills, communication skills, analytical ...  Delhi NCR(Vikas Puri)   
1  ppc, logistics, inventory management, supply c...                Sonepat   
2  HR Analytics, Employee Engagement, Training, S...              Delhi NCR   
3  SQL, Javascript, Automation, Python, Ruby, Ana...              Bengaluru   
4  accounting, finance, cash flow, financial plan...                Gurgaon   

   salary  company_name_encoded  
0   6to10                  3687  
1  10to15                   458  
2  15to25                  4195  
3  10to15                   313  
4    3to6                  1305

In [7]:

scientist_sal.columns

Index(['Unnamed: 0', 'experience', 'job_description', 'job_desig', 'job_type',
       'key_skills', 'location', 'salary', 'company_name_encoded'],
      dtype='object')

In [8]:
# splitting experience into min_experience and max_experience and converting it to numeric
scientist_sal[['min_experience', 'max_experience']] = scientist_sal['experience'].str.split('-', expand=True)
scientist_sal['min_experience'] = scientist_sal['min_experience'].str.extract('(\d+)').astype(float)
scientist_sal['max_experience'] = scientist_sal['max_experience'].str.extract('(\d+)').astype(float)

In [9]:
scientist_sal.drop('experience', axis=1, inplace=True)

In [10]:

# Label encoding
columns = ['job_description', 'job_desig', 'job_type', 'key_skills', 'location', 'salary']
label_encoders = {}
for col in columns:
    le = LabelEncoder()
    scientist_sal[col] = le.fit_transform(scientist_sal[col].astype(str))
    label_encoders[col] = le

In [11]:
X = scientist_sal.drop('salary', axis=1)
y = scientist_sal['salary']

In [12]:
#split test train, test=0.2
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [13]:

#classifiers
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier(n_estimators=100)
clf3 = ExtraTreesClassifier(n_estimators=100)
clf4 = AdaBoostClassifier(n_estimators=100)
clf5 = GradientBoostingClassifier(n_estimators=100)

In [14]:

#pipelines
pipe1 = Pipeline([('clf', clf1)])
pipe2 = Pipeline([('clf', clf2)])
pipe3 = Pipeline([('clf', clf3)])
pipe4 = Pipeline([('clf', clf4)])
pipe5 = Pipeline([('clf', clf5)])

In [15]:
#params
param1 = {'max_depth': [3, 5, 10, None], 'min_samples_split': [2, 5, 10]}
param2 = {'n_estimators': [50, 100, 150], 'max_depth': [5, 10, None]}
param3 = {'n_estimators': [50, 100, 150], 'max_depth': [5, 10, None]}
param4 =  {'n_estimators': [50, 100, 150], 'learning_rate': [0.5, 1.0, 1.5]}
param5 = {'n_estimators': [50, 100, 150], 'learning_rate': [0.05, 0.1, 0.2], 'max_depth': [3, 5, 7]}

In [16]:
#training each classifier
classifiers = [clf1, clf2, clf3, clf4, clf5]
names = ['DecisionTree', 'RandomForest', 'ExtraTrees', 'AdaBoost', 'GradientBoosting']
for clf, name in zip(classifiers,names):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    # printing accuracy and confusion matrix
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc}")
    print(f"Confusion Matrix for {name}:\n{confusion_matrix(y_test, y_pred)}")
    print("-" * 50)

DecisionTree Accuracy: 0.3668265589497602
Confusion Matrix for DecisionTree:
[[353  46  19   3 147  70]
 [ 32 300 251  33  81 189]
 [ 29 264 305 129  36 114]
 [  3  39 105 139   3  17]
 [139  64  35   4 171 130]
 [ 60 190 107  16 153 185]]
--------------------------------------------------
RandomForest Accuracy: 0.4034334763948498
Confusion Matrix for RandomForest:
[[450  30  11   0 101  46]
 [ 36 348 270   7  48 177]
 [ 20 327 319 115  17  79]
 [  4  16 123 157   1   5]
 [169  52  21   0 168 133]
 [ 63 252  82   7 151 156]]
--------------------------------------------------
ExtraTrees Accuracy: 0.37919717243120427
Confusion Matrix for ExtraTrees:
[[431  29  15   0 114  49]
 [ 36 321 269   8  42 210]
 [ 18 335 287 138  15  84]
 [  5  15 125 154   2   5]
 [168  54  24   2 167 128]
 [ 61 267  85   7 149 142]]
--------------------------------------------------
AdaBoost Accuracy: 0.4067154758899268
Confusion Matrix for AdaBoost:
[[493  24  12   1  55  53]
 [ 36 322 277  25  55 171]
 [ 19 2

In [17]:

# we can say that gradient boosting is performing better than all other classifiers